server:
  port: 18761

spring:
  application:
    name: eureka-client

eureka:
  instance:
    #向eureka server注册访问此服务的地址，即http://client.eureka.com:18761访问当前服务
    hostname: client.eureka.com
    lease-renewal-interval-in-seconds: 5
    #ip方式注册
#    prefer-ip-address: true
    #ip地址
#    ip-address: xxx.xxx.xxx.xxx
  client:
    service-url:
      defaultZone: http://server.node1.eureka.com:8761/eureka/,http://server.node2.eureka.com:8762/eureka/
