spring:
  application:
    name: feign-hystrix

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://server.node1.eureka.com:8761/eureka/,http://server.node2.eureka.com:8762/eureka/

# 【开启断路器】：
#         feign是自带断路器hystrix的，只是没有默认打开hystrix。需要在配置文件中配置打开，将feign.hystrix.enabled设置为true，则hystrix断路器方可生效
# 【是否配置了 feign.hystrix.enabled ，页面显示的异常信息是不同的】：
#         1、如果配置了feign.hystrix.enabled，且值为false，则访问的时候，页面会报Connection refused的错误，比如：Connection refused: connect executing GET http://sea-service-user/person/1
#         2、如果没有配置feign.hystrix.enabled，则访问的时候，页面会报客户端异常，比如：com.netflix.client.ClientException: Load balancer does not have available server for client: sea-service-user
feign:
  compression:
    #响应GZIP压缩
    response:
      enabled: true
    #请求GZIP压缩
    request:
      enabled: true
      #压缩支持的MIME TYPE
      mime-types: ["text/html","application/xml","application/json"]
      #压缩数据大小的下限
      min-request-size: 2048
  hystrix:
    enabled: true

#服务的application-name
#此配置是针对单个服务(eureka-client)的负载均衡策略配置
eureka-client:
  ribbon:
    #Ribbon负载均衡策略
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#turbine:
#  #配置需要监控的服务名
#  app-config: eureka-client,eureka-client2
#  aggregator:
#    #指定聚合哪些集群，多个使用","分割，默认为default。可使用http://.../turbine.stream?cluster={clusterConfig之一}访问
#    cluster-config: default
#  # 1. clusterNameExpression指定集群名称，默认表达式appName；此时：turbine.aggregator.clusterConfig需要配置想要监控的应用名称
#  # 2. 当clusterNameExpression: default时，turbine.aggregator.clusterConfig可以不写，因为默认就是default
#  # 3. 当clusterNameExpression: metadata['cluster']时，假设想要监控的应用配置了eureka.instance.metadata-map.cluster: ABC，则需要配置，同时turbine.aggregator.clusterConfig: ABC
#  cluster-name-expression: new String("default")
