server:
  port: 1115

spring:
  application:
    #应用名称
    name: config-server
  cloud:
    config:
      #分支
      label: test
      server:
        git:
          #仓库地址
          #可以通过{application}占位符实现一个应用对应一个git仓库目录的配置效果
          #会根据客户端的spring.application.name信息来填充{application}
          #uri: https://github.com/hansonwang99/{application}
          uri: https://github.com/EverHE/config-repo.git
          #用户名
          username: aaa@hotmail.com
          #密码
          password: aaa
          #仓库路径
          #search-paths: respo
          #配置中心远程clone下来的配置文件所在的位置。默认情况下，它们放在系统临时目录中，前缀为config-repo-。(linux，/tmp/config-repo-xxx)
          basedir: c:\\temp

## 为了让config server实现集群、高可用，则需要配置eureka注册中心
#eureka:
#  instance:
#    hostname: localhost # 服务提供者应用所在的主机（本地测试的话，使用localhost或者127.0.0.1即可，或者在host文件中指定一个虚拟域名也可以）
#    #lease-renewal-interval-in-seconds: 5 # 心跳时间，表示eureka client发送心跳给eureka server端的频率（缺省为30s）
#  client:
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/eureka # 指定eureka服务器集群列表地址
